//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P1A.Theatre.Square.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("P1A.Theatre.Square.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid a value.
        /// </summary>
        internal static string invalid_a {
            get {
                return ResourceManager.GetString("invalid_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input values.
        /// </summary>
        internal static string invalid_inputs {
            get {
                return ResourceManager.GetString("invalid_inputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid m value.
        /// </summary>
        internal static string invalid_m {
            get {
                return ResourceManager.GetString("invalid_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid n value.
        /// </summary>
        internal static string invalid_n {
            get {
                return ResourceManager.GetString("invalid_n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theatre Square in the capital city of Berland has a rectangular shape with the size n × m meters. On the occasion of the city&apos;s anniversary, a decision was taken to pave the Square with square granite flagstones. Each flagstone is of the size a × a.
        ///
        ///What is the least number of flagstones needed to pave the Square? It&apos;s allowed to cover the surface larger than the Theatre Square, but the Square has to be covered. It&apos;s not allowed to break the flagstones. The sides of flagstones should be parallel to the s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string specification {
            get {
                return ResourceManager.GetString("specification", resourceCulture);
            }
        }
    }
}
